name: Build and Push Docker Image

env:
  REPOSITORY: registry.digitalocean.com/nodirbyte/xan-pro-backend
  PROJECT_DIR: /root/pro/backend

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Login (DigitalOcean)
        uses: docker/login-action@v3.3.0
        with:
          registry: registry.digitalocean.com
          username: ${{ secrets.DO_USERNAME }}
          password: ${{ secrets.DO_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.REPOSITORY }}:latest

  deploy:
    runs-on: self-hosted
    needs: build
    defaults:
      run:
        working-directory: ${{ env.PROJECT_DIR }}
    steps:
      - name: Docker Login (DigitalOcean)
        run: echo "${{ secrets.DO_USERNAME }}" | docker login registry.digitalocean.com -u ${{ secrets.DO_PASSWORD }} --password-stdin

      - name: Pull the latest image
        run: |
          echo "Pull the latest image"
          docker pull ${{ env.REPOSITORY }}:latest
      - name: Migrate
        run: |
          echo "Applying migrations"
          docker compose -f docker-compose.yml run -i --rm backend python3 manage.py migrate
      - name: Restart
        run: |
          echo "Restarting services"
          docker compose -f docker-compose.yml up backend -d
          docker compose -f docker-compose.yml up backend-schedule -d
          docker compose -f docker-compose.yml up customer_bot -d
      - name: Show processes
        run: |
          docker compose ps --all --format "table {{.ID}}\t{{.Service}}\t{{.State}}\t{{.Status}}\t{{.CreatedAt}}"
